/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_estructuras;

import javax.swing.JOptionPane;

/**
 *
 * @author Antho
 */
public class Ventana2 extends javax.swing.JFrame{

    private Grafo grafoVentana2;

    /**
     * Creates new form Ventana2
     */
    public Ventana2(){
        initComponents();
        this.grafoVentana2 = null;
    }

    public Ventana2(Grafo grafoRecibido){
        initComponents();
        this.grafoVentana2 = grafoRecibido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BotonSiguiente2 = new javax.swing.JButton();
        Mostrar_PerfilesVentana2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CrearPerfil = new javax.swing.JButton();
        EliminarPerfil = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 10, 70, -1));

        BotonSiguiente2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        BotonSiguiente2.setText("Siguiente");
        jPanel1.add(BotonSiguiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 90, -1));

        Mostrar_PerfilesVentana2.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        Mostrar_PerfilesVentana2.setText("Representación de los Perfiles");
        Mostrar_PerfilesVentana2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_PerfilesVentana2ActionPerformed(evt);
            }
        });
        jPanel1.add(Mostrar_PerfilesVentana2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 230, 30));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel1.setText("Central de Edicición");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel2.setText("Aquí podrás editar todo lo referente a los perfiles: desde crear un nuevo perfil o eliminarlo, hasta agregar o eliminar una relación.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 450, 160));

        CrearPerfil.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        CrearPerfil.setText("Crear Nuevo Perfil");
        CrearPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(CrearPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 170, 30));

        EliminarPerfil.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        EliminarPerfil.setText("Eliminar un Perfil");
        EliminarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, 30));

        jButton4.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jButton4.setText("Agregar una Amistad a un Perfil");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 240, 30));

        jButton5.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jButton5.setText("Eliminar una Amistad de un Perfil");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mostrar_PerfilesVentana2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_PerfilesVentana2ActionPerformed
        // TODO add your handling code here:
        this.jTextArea1.setText(this.grafoVentana2.Recorrer());


    }//GEN-LAST:event_Mostrar_PerfilesVentana2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EliminarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPerfilActionPerformed
        // TODO add your handling code here:
        String Usuario = ""; 
        boolean EsValido = false;   
        boolean Cancelado = false;
        
        while(!EsValido && !Cancelado){
            Usuario = JOptionPane.showInputDialog(this,"Ingrese el nombre del nuevo usuario que desea eliminar (ej: @Juan_gomez07):","Eliminar Perfil",JOptionPane.PLAIN_MESSAGE);
            
            try{
                if (Usuario == null){
                    Cancelado = true;
                }else{
                    Usuario = Usuario.trim();
                    if (Usuario.isEmpty()){
                        JOptionPane.showMessageDialog(this,"El nombre de usuario no puede estar vacío.","Error de Formato",JOptionPane.ERROR_MESSAGE);

                    }else if(!Usuario.startsWith("@")){
                        JOptionPane.showMessageDialog(this,"El nombre de usuario DEBE comenzar con '@'.","Error de Formato",JOptionPane.ERROR_MESSAGE);

                    }else if (Usuario.contains(" ")){
                        JOptionPane.showMessageDialog(this,"El nombre de usuario no puede contener espacios.","Error de Formato",JOptionPane.ERROR_MESSAGE);
                    }else{
                        EsValido = true; 
                    }
                }

            }catch (Exception e){
                Cancelado = true;
            }
        }

        if (EsValido == true) {
            this.grafoVentana2.EliminarNodo(Usuario); 
            JOptionPane.showMessageDialog(this, "¡Usuario '" + Usuario + "' eliminado con éxito!");
        }

        
        
        
    }//GEN-LAST:event_EliminarPerfilActionPerformed

    private void CrearPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPerfilActionPerformed
        // TODO add your handling code here:
        String Usuario = ""; 
        boolean EsValido = false;   
        boolean Cancelado = false;
        
        while(!EsValido && !Cancelado){
            Usuario = JOptionPane.showInputDialog(this,"Ingrese el nombre del nuevo usuario que desea crear (ej: @Aran_Pereira):","Agregar Perfil",JOptionPane.PLAIN_MESSAGE);
            
            try{
                if (Usuario == null){
                    Cancelado = true;
                }else{
                    Usuario = Usuario.trim();
                    if (Usuario.isEmpty()){
                        JOptionPane.showMessageDialog(this,"El nombre de usuario no puede estar vacío.","Error de Formato",JOptionPane.ERROR_MESSAGE);

                    }else if(!Usuario.startsWith("@")){
                        JOptionPane.showMessageDialog(this,"El nombre de usuario DEBE comenzar con '@'.","Error de Formato",JOptionPane.ERROR_MESSAGE);

                    }else if (Usuario.contains(" ")){
                        JOptionPane.showMessageDialog(this,"El nombre de usuario no puede contener espacios.","Error de Formato",JOptionPane.ERROR_MESSAGE);
                    }else{
                        EsValido = true; 
                    }
                }

            } catch (Exception e){
                Cancelado = true;
            }
        }

        if (EsValido == true) {
            this.grafoVentana2.NuevoNodo(Usuario); 
            JOptionPane.showMessageDialog(this, "¡Usuario '" + Usuario + "' creado con éxito!");
        }


    }//GEN-LAST:event_CrearPerfilActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSiguiente2;
    private javax.swing.JButton CrearPerfil;
    private javax.swing.JButton EliminarPerfil;
    private javax.swing.JButton Mostrar_PerfilesVentana2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
