/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_estructuras;

import javax.swing.JOptionPane;
/**
 *
 * @author Rafael Álvarez
 */
public class Ventana3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana3.class.getName());

    /**
     * Creates new form Ventana3
     */
    private String resultadoKosaraju;
    private Grafo grafoOriginal;
    private String RespaldoVentana3;
    
    
    public Ventana3(Grafo grafo_original,String resultado_recibido, String Respaldo_V3) {
        initComponents();
        this.grafoOriginal = grafo_original;
        this.resultadoKosaraju = resultado_recibido;
        this.RespaldoVentana3 = Respaldo_V3;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    
 private void MostrarResultados(String resultado) {
                Resultados.setText(resultado);
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Etiqueta_amistades = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultados = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Imprimir_amistades = new javax.swing.JButton();
        Imprimir_el_grafo = new javax.swing.JButton();
        Devolverse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 421));
        setSize(new java.awt.Dimension(700, 421));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Etiqueta_amistades.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        Etiqueta_amistades.setText("Amistades");
        jPanel1.add(Etiqueta_amistades, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        Resultados.setColumns(20);
        Resultados.setRows(5);
        jScrollPane1.setViewportView(Resultados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 580, 160));

        jLabel2.setText("Los grupos de amistades presentes (relaciones fuertemente enlazadas) en la aplicacion son:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        Imprimir_amistades.setText("Imprimir grupos de amistades");
        Imprimir_amistades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imprimir_amistadesActionPerformed(evt);
            }
        });
        jPanel1.add(Imprimir_amistades, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        Imprimir_el_grafo.setText("Imprimir el Grafo ");
        Imprimir_el_grafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imprimir_el_grafoActionPerformed(evt);
            }
        });
        jPanel1.add(Imprimir_el_grafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        Devolverse.setText("Atrás");
        Devolverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolverseActionPerformed(evt);
            }
        });
        jPanel1.add(Devolverse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Imprimir_amistadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imprimir_amistadesActionPerformed
        // TODO add your handling code here:
        this.Resultados.setText(this.resultadoKosaraju);
    }//GEN-LAST:event_Imprimir_amistadesActionPerformed

    private void Imprimir_el_grafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imprimir_el_grafoActionPerformed
        // TODO add your handling code here:
        ImpresionGrafo.MostrarGrafoVisualizado(this.grafoOriginal);
        
       JOptionPane.showMessageDialog(this,
               "Las esferas que tengan el mismo color respresentan que estan fuertemente enlazadas",
               "NOTA", 
               JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Imprimir_el_grafoActionPerformed

    private void DevolverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolverseActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Ventana2 ventanaOperaciones = new Ventana2(this.grafoOriginal, this.RespaldoVentana3);
        ventanaOperaciones.setVisible(true);
    ventanaOperaciones.setLocationRelativeTo(null);
    }//GEN-LAST:event_DevolverseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Devolverse;
    private javax.swing.JLabel Etiqueta_amistades;
    private javax.swing.JButton Imprimir_amistades;
    private javax.swing.JButton Imprimir_el_grafo;
    private javax.swing.JTextArea Resultados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
